# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dafca7ba900753a24cd2fad2f701cd993ba7f6b6a3ad6d7be33afd7c6e6459370fe679affcd6c1685d8262a8b1ae9bb7cb87a3983597725b5ad4ccb0724ed51b

test:
  secret_key_base: dfce891fb15e96e74ff30b053c512ecaa71b96b0a4267f338b447f58e66741f44f8826f110aa2f230128d9e0c04f0d6eed0ddcbc8593402374ae9d30c60fe7ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
